services:
  front:
    build:
      context: ../../front_GTIO_VotingSystem
      dockerfile: ../DockerConfig/FRONT/Dockerfile
    container_name: front
    networks:
      frontend_net:
        ipv4_address: 172.20.0.2
    ports:
      - "4200:4200"
    volumes:
      - ../../front_GTIO_VotingSystem:/app
    working_dir: /app
    command: ng serve --host 0.0.0.0

networks:
  frontend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
