services:
  back:
    build:
      context: ../../BackEnd
      dockerfile: BackEnd/Dockerfile
    container_name: back
    networks:
      bbdd_backend_net:
        ipv4_address: 172.18.0.3
    ports:
      - "44363:44363"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  bbdd_backend_net:
    external: true
