variable "service_name" {}
variable "cluster_id" {}
variable "task_family_name" {}
variable "task_revision" {}
variable "subnet_ids" {}
variable "security_group_id" {}
variable "target_group_arn" {}
variable "container_name" {}
variable "container_port" {}