name: CI/CD Pipeline

on:
  push:
    branches:
      - productive
  pull_request:
    branches:
      - productive
env:
  AWS_REGION: us-east-1
  ECR_FRONT_REPO: 024663765236.dkr.ecr.us-east-1.amazonaws.com/front
  # ECR_BACK_REPO: <tu_id_ecr>.dkr.ecr.us-east-1.amazonaws.com/back

jobs:
  run_backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies (Backend)
        run: dotnet restore BackEnd/BackEnd/

      - name: Check code formatting (Backend)
        run: dotnet format --verify-no-changes || echo "⚠️ Code format issues found!"

      - name: Check for outdated dependencies (Backend)
        run: dotnet list package --outdated || echo "⚠️ Some dependencies are outdated!"

      - name: Build project (Backend)
        run: dotnet build BackEnd/BackEnd/ --no-restore --configuration Release

      - name: Run tests with coverage (Backend)
        run: dotnet test BackEnd/Test/ --configuration Release --collect:"XPlat Code Coverage"

      - name: Upload test coverage report (Backend)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-backend
          path: BackEnd/Test/TestResults/

      - name: Publish project (Backend)
        run: dotnet publish BackEnd/BackEnd/ --configuration Release --output ./publish-backend

      - name: Upload build artifact (Backend)
        uses: actions/upload-artifact@v4
        with:
          name: published-backend
          path: ./publish-backend

  # Job para ejecutar pruebas del Frontend
  run_frontend_tests:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
  
      - name: Install dependencies
        run: |
          cd front_GTIO_VotingSystem
          npm install
  
      - name: Run Angular tests
        run: |
          cd front_GTIO_VotingSystem
          npm test -- --no-watch --browsers=ChromeHeadless --code-coverage
  
      - name: Upload test coverage report (Frontend)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: front_GTIO_VotingSystem/coverage/

  create_ecr:
    name: Crear repositorio ECR con Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TerraFormConfig/ECR
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Verificar configuración de AWS
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Capturar URI del ECR
        id: ecr_output
        run: echo "ECR_REPO=$(terraform output -raw ecr_repo_url)" >> $GITHUB_OUTPUT
    outputs:
      ecr_repo: ${{ steps.ecr_output.outputs.ECR_REPO }}

        
  build-images:
    name: Build Docker Images (Front & Back)
    runs-on: ubuntu-latest
    needs: [run_backend_tests, run_frontend_tests,create_ecr]
    #if: |
     # github.event_name == 'push' && contains(github.event.head_commit.message, 'imagen')
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Set up Docker Compose
        run: docker compose version
  
      - name: Build only front and back services
        working-directory: DockerConfig
        run: |
          docker compose -f compose.yaml build front back kong  # Construye las imágenes front y back
  
      - name: List Docker images
        run: docker images  # Muestra las imágenes disponibles en Docker para depuración
  
      - name: Save backend image in BackEnd/BackEnd
        run: |
          docker save dockerconfig-back > BackEnd/BackEnd/DockerFile
      
      - name: Save frontend image in front_GTIO_VotingSystem
        run: |
          docker save dockerconfig-front > front_GTIO_VotingSystem/DockerFile

  deploy:
    name: Subir imágenes a ECR
    needs: [create_ecr, run_backend_tests, run_frontend_tests, build-images]
    runs-on: ubuntu-latest
    env:
      ECR_REPO: ${{ needs.create_ecr.outputs.ecr_repo }}
      AWS_REGION: us-east-1
    steps:
      - name: Login en ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - name: Construir y subir imagen FRONT
        working-directory: front_GTIO_VotingSystem
        run: |
          docker build -t front .
          docker tag dockerconfig-front:latest $ECR_REPO:front
          docker push $ECR_REPO:front

      - name: Construir y subir imagen BACK
        working-directory: BackEnd/BackEnd
        run: |
          docker build -t back .
          docker tag dockerconfig-back:latest $ECR_REPO:back
          docker push $ECR_REPO:back
