name: Run Tests on Merge

on:
  push:
    branches:
      - test 

jobs:
  test:
    name: Run .NET Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore BackEnd/BackEnd/

      - name: Build project
        run: dotnet build BackEnd/BackEnd/ --no-restore --configuration Release

      - name: Run tests
        run: dotnet test BackEnd/Test/ --no-build --configuration Release --no-build --configuration Release --logger "console;verbosity=detailed"
